BigMixer = Scails::ControlMap.new(:master    => { :level => 7,
                                                  :return_1 => 116,
                                                  :return_2 => 117,
                                                  :return_3 => 118,
                                                  :return_4 => 119},
                                     :channel_1 => {:level =>  8,
                                                    :pan   =>  23,
                                                    :send_1 => 39,
                                                    :send_2 => 53,
                                                    :send_3 => 102,
                                                    :bass => 68,
                                                    :treble => 82},
                                     :channel_2 => {:level =>  9,
                                                    :pan   =>  24,
                                                    :send_1 => 40,
                                                    :send_2 => 54,
                                                    :send_3 => 103,
                                                    :bass => 69,
                                                    :treble => 83},
                                     :channel_3 => {:level =>  10,
                                                    :pan   =>  25,
                                                    :send_1 => 41,
                                                    :send_2 => 55,
                                                    :send_3 => 104,
                                                    :bass => 70,
                                                    :treble => 84},
                                     :channel_4 => {:level =>  12,
                                                    :pan   =>  26,
                                                    :send_1 => 42,
                                                    :send_2 => 56,
                                                    :send_3 => 105,
                                                    :bass => 71,
                                                    :treble => 85},
                                     :channel_5 => {:level =>  13,
                                                    :pan   =>  27,
                                                    :send_1 => 43,
                                                    :send_2 => 57,
                                                    :send_3 => 106,
                                                    :bass => 72,
                                                    :treble => 86},
                                     :channel_6 => {:level =>  13,
                                                    :pan   =>  28,
                                                    :send_1 => 44,
                                                    :send_2 => 58,
                                                    :send_3 => 107,
                                                    :bass => 73,
                                                    :treble => 87},
                                     :channel_7 => {:level =>  13,
                                                    :pan   =>  29,
                                                    :send_1 => 45,
                                                    :send_2 => 59,
                                                    :send_3 => 108,
                                                    :bass => 74,
                                                    :treble => 88},
                                     :channel_8 => {:level =>  13,
                                                    :pan   =>  30,
                                                    :send_1 => 46,
                                                    :send_2 => 60,
                                                    :send_3 => 109,
                                                    :bass => 75,
                                                    :treble => 89},
                                     :channel_9 => {:level =>  13,
                                                    :pan   =>  31,
                                                    :send_1 => 47,
                                                    :send_2 => 61,
                                                    :send_3 => 110,
                                                    :bass => 76,
                                                    :treble => 90},
                                     :channel_10 => {:level =>  13,
                                                     :pan   =>  33,
                                                     :send_1 => 48,
                                                     :send_2 => 62,
                                                     :send_3 => 111,
                                                     :bass => 77,
                                                     :treble => 91},
                                     :channel_11 => {:level =>  13,
                                                     :pan   =>  34,
                                                     :send_1 => 49,
                                                     :send_2 => 63,
                                                     :send_3 => 112,
                                                     :bass => 78,
                                                     :treble => 92},
                                     :channel_12 => {:level =>  13,
                                                     :pan   =>  35,
                                                     :send_1 => 50,
                                                     :send_2 => 65,
                                                     :send_3 => 113,
                                                     :bass => 79,
                                                     :treble => 93},
                                     :channel_13 => {:level =>  13,
                                                     :pan   =>  36,
                                                     :send_1 => 51,
                                                     :send_2 => 66,
                                                     :send_3 => 114,
                                                     :bass => 80,
                                                     :treble => 94},
                                     :channel_14 => {:level =>  13,
                                                     :pan   =>  37,
                                                     :send_1 => 52,
                                                     :send_2 => 67,
                                                     :send_3 => 115,
                                                     :bass => 81,
                                                     :treble => 95})
