NN_19 = Scails::ControlMap.new(:modulation_wheel => 1,
                               :portamento => 5,
                               :ext_mod_select => 43,
                               :master => {:level => 7},
                               :amp => {:env => {:attack  => 73,
                                                 :decay   => 9, 
                                                 :release => 72,
                                                 :sustain => 12},
                                        :ext_mod          => 42,
                                        :velocity_amount => 45,
                                        :attack_velocity_amount => 48,
                                        :mod_wheel_amount => 36},
                               :filter => {:env => {:attack  => 14,
                                                    :decay   => 15,
                                                    :sustain => 16,
                                                    :release => 17,
                                                    :amount  => 18,
                                                    :velocity_amount => 46,
                                                    :decay_velocity_amount => 47,
                                                    :invert  => 19},
                                           :resonance => 71,
                                           :frequency => 74,
                                           :on        => 75,
                                           :mode      => 76,
                                           :keyboard_track => 77,
                                           :frequency_mod_wheel_amount => 33,
                                           :frequency_ext_mod          => 40,
                                           :resonance_mod_wheel_amount => 34,
                                           :decay_mod_wheel_amount     => 35},
                               :sample => {:start => 20,
                                           :start_velocity_amount => 49},
                               :osc => {:octave         => 21,
                                        :semitone       => 22,
                                        :fine_tune      => 23,
                                        :env_amount     => 24,
                                        :keyboard_track => 25},
                               :lfo => {:rate        => 26,
                                        :amount      => 27,
                                        :wave        => 28,
                                        :destination => 29,
                                        :sync_enable => 30,
                                        :mod_wheel_amount  => 37,
                                        :ext_mod     => 41},
                               :pitch_bend_range => 39,
                               :solo_sample      => 55,
                               :spread_mode      => 56,
                               :stereo_spread    => 57,
                               :key_mode         => 68})
